winner_socer: 2
teams:
  blue:
    color: "§9"
    name: "蓝队"
  red:
    color: "§c"
    name: "红队"

default-items:
  - "STONE_SWORD:1"
  - "STONE_PICKAXE:1"
  - "STONE_SPADE:1"

blocks:
  - "草方块:简单:GRASS_BLOCK"
  - "泥土:简单:DIRT"
  - "石头:简单:STONE"
  - "沙子:简单:SAND"
  - "沙砾:简单:GRAVEL"
  - "煤炭矿石:简单:COAL_ORE"
  - "铁矿石:简单:IRON_ORE"
  - "金矿石:简单:GOLD_ORE"
  - "钻石矿石:简单:DIAMOND_ORE"
  - "红石矿石:简单:REDSTONE_ORE"
  - "青金石矿石:简单:LAPIS_ORE"
  - "绿宝石矿石:简单:EMERALD_ORE"
  - "熔岩:困难:LAVA"
  - "水:简单:WATER"
  - "玻璃:简单:GLASS"
  - "玻璃板:简单:GLASS_PANE"
  - "木门:简单:OAK_DOOR"
  - "铁门:简单:IRON_DOOR"
  - "书架:简单:BOOKSHELF"
  - "工作台:简单:CRAFTING_TABLE"
  - "熔炉:简单:FURNACE"
  - "箱子:简单:CHEST"
  - "床:简单:BED"
  - "铁轨:简单:RAILS"
  - "火把:简单:TORCH"
  - "红石火把:简单:REDSTONE_TORCH"
  - "工作台:简单:LOOM"
  - "台灯:简单:SEA_LANTERN"
  - "雪:简单:SNOW"
  - "冰:简单:ICE"
  - "雪块:简单:SNOW_BLOCK"
  - "苔藓:简单:MOSS_BLOCK"
  - "铁栅栏:简单:IRON_BARS"
  - "草叶:简单:TALL_GRASS"
  - "玉米:简单:BEETROOTS"
  - "西瓜:简单:MELON"
  - "南瓜:简单:PUMPKIN"
  - "竹子:简单:BAMBOO"
  - "南瓜灯:简单:PUMPKIN_LANTERN"
  - "金块:简单:GOLD_BLOCK"
  - "铁块:简单:IRON_BLOCK"
  - "钻石块:简单:DIAMOND_BLOCK"
  - "绿宝石块:简单:EMERALD_BLOCK"
  - "红石块:简单:REDSTONE_BLOCK"
  - "青金石块:简单:LAPIS_BLOCK"
  - "瓷砖:简单:BRICK_BLOCK"
  - "黑曜石:困难:OBSIDIAN"
  - "紫水晶:简单:AMETHYST_BLOCK"
  - "末地石:困难:END_STONE"
  - "末地宝珠:困难:END_PORTAL_FRAME"
  - "海晶石:简单:PRISMARINE"
  - "海晶灯:简单:PRISMARINE_LANTERN"
  - "末地水晶:困难:END_CRYSTAL"
  - "末影箱:简单:ENDER_CHEST"
  - "末影珍珠:简单:ENDER_PEARL"
  - "橡木:简单:OAK_LOG"
  - "白桦木:简单:SPRUCE_LOG"
  - "丛林木:简单:JUNGLE_LOG"
  - "金合欢木:简单:ACACIA_LOG"
  - "深色橡木:简单:DARK_OAK_LOG"
  - "蘑菇:简单:BROWN_MUSHROOM"
  - "红蘑菇:简单:RED_MUSHROOM"
  - "树苗:简单:OAK_SAPLING"
  - "白桦树苗:简单:SPRUCE_SAPLING"
  - "丛林树苗:简单:JUNGLE_SAPLING"
  - "金合欢树苗:简单:ACACIA_SAPLING"
  - "深色橡木树苗:简单:DARK_OAK_SAPLING"
  - "草丛:简单:GRASS"
  - "树叶:简单:LEAVES"
  - "石砖:简单:STONE_BRICKS"
  - "苔石砖:简单:MOSSY_STONE_BRICKS"
  - "裂石砖:简单:CRACKED_STONE_BRICKS"
  - "砖块:简单:BRICK_BLOCK"
  - "黑曜石:困难:OBSIDIAN"
  - "末地石:简单:END_STONE"
  - "末影水晶:困难:END_CRYSTAL"
  - "红色羊毛:简单:RED_WOOL"
  - "绿色羊毛:简单:LIME_WOOL"
  - "蓝色羊毛:简单:BLUE_WOOL"
  - "白色羊毛:简单:WHITE_WOOL"
  - "羊毛:简单:WOOL"
  - "草方块:简单:GRASS_BLOCK"
  - "金矿:简单:GOLD_ORE"
  - "铁矿:简单:IRON_ORE"
  - "钻石矿:简单:DIAMOND_ORE"
  - "羊毛块:简单:WOOL_BLOCK"
  - "末影宝石:简单:ENDER_CRYSTAL"
  - "红石矿石:简单:REDSTONE_ORE"
  - "海晶石:简单:PRISMARINE"
  - "海晶灯:简单:PRISMARINE_LANTERN"
  - "紫水晶矿石:简单:AMETHYST_ORE"
  - "火焰:困难:FIRE"
  - "金合欢木:简单:ACACIA_WOOD"
  - "丛林木:简单:JUNGLE_WOOD"
  - "深色橡木:简单:DARK_OAK_WOOD"
  - "羊毛方块:简单:WOOL_BLOCK"
  - "青金石矿:简单:LAPIS_ORE"
  - "金块:简单:GOLD_BLOCK"
  - "铁块:简单:IRON_BLOCK"
  - "钻石块:简单:DIAMOND_BLOCK"
